Add the Item API
CodeUtilities/CodeUtilities pull request #55
Opened 2022-05-03 12:18 UTC by RedCommand-dev

2022-05-04 19:09 UTC, BlazeMCworld requested changes

2022-05-04 19:09 UTC, BlazeMCworld commented on src/main/java/io/github/codeutilities/CodeUtilities.java
> +        new SocketHandler();
should probably be loader.load, besides that code should be good even tho i didnt test it

2022-05-05 08:11 UTC, RedCommand-dev commented
Changed and tester, works.

2022-05-06 05:40 UTC, TechStreetDev submitted a review, later dismissed
LGTM

2022-05-06 08:39 UTC, DaMan56100 commented on .github/workflows/build.yml
> +permissions: write-all
um?

2022-05-06 14:35 UTC, TechStreetDev approved these changes

2022-05-06 14:36 UTC, BlazeMCworld approved these changes

2022-05-06 14:38 UTC, merged