new scriptaction stuff
CodeUtilities/CodeUtilities pull request #71
Opened 2022-05-03 17:38 UTC by Excuze

Simple actions, I made it during school on a school laptop that hits 20 fps so don't judge me ;-;

Create Dict now has two optional list arguments to initialize as keys/values like in DiamondFire

Added If Matches Regex to text actions

Added Append List Values - copies and appends the contents of one list to another. Also from DiamondFire

2022-05-04 19:11 UTC, BlazeMCworld requested changes

2022-05-04 19:11 UTC, BlazeMCworld commented on src/main/java/io/github/codeutilities/script/action/ScriptActionType.java
> +            .arg("Other List", ScriptActionArgumentType.VARIABLE)
should be ScriptActionArgumentType.LIST for "Other List"

2022-05-04 19:11 UTC, BlazeMCworld commented on src/main/java/io/github/codeutilities/script/action/ScriptActionType.java
> +                    int lowerLength = (keys.size() < values.size()) ? keys.size() : values.size();
Math.min() is a thing btw

2022-05-04 21:11 UTC, Excuze commented
will do these once exam is over probably

2022-05-04 23:29 UTC, Excuze commented on src/main/java/io/github/codeutilities/script/action/ScriptActionType.java
> +                    int lowerLength = (keys.size() < values.size()) ? keys.size() : values.size();
changed

2022-05-05 07:20 UTC, TechStreetDev approved these changes
LGTM

2022-05-05 11:03 UTC, BlazeMCworld approved these changes

2022-05-05 11:05 UTC, merged